# Generated by Django 4.0.4 on 2022-06-22 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='detalle_venta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('productos', models.CharField(max_length=50)),
                ('total', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=200)),
                ('valor_p', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='suscriptor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('correo', models.CharField(max_length=50)),
                ('fono', models.IntegerField()),
                ('direccion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='venta',
            fields=[
                ('fecha', models.DateTimeField(auto_created=True)),
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('detalle_ventas', models.CharField(max_length=50)),
                ('total_venta', models.IntegerField()),
                ('descuento', models.IntegerField()),
                ('iva', models.IntegerField()),
                ('total', models.IntegerField()),
            ],
        ),
    ]
